language: java
before_install:
  - "git clone https://github.com/MIND-Tools/mind-parent.git"
  - "cd mind-parent"
  - "mvn -U install"
  - "cd .."    
install: 
  - "mvn -U clean -PCI-profile"
script: 
  - "mvn -U verify -PCI-profile"
