language: java
before_install:
  - "git clone https://github.com/MIND-Tools/maven.git"
  - "cd maven/mind-parent"
  - "mvn -U install"
  - "cd ../.."    
install: 
  - "mvn -U clean -PCI-profile"
script: 
  - "mvn -U verify -PCI-profile"
